src/Entity/Actualite.php
<?php

namespace App\Entity;

use App\Repository\ActualiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActualiteRepository::class)]
class Actualite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\OneToMany(mappedBy: 'comments', targetEntity: Commentaire::class)]
    private Collection $commentaire;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(nullable: true)]
    private ?int $Likes = null;

    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setComments($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getComments() === $this) {
                $commentaire->setComments(null);
            }
        }

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }
    public function __toString()
{
    return $this->getTitre(); // or whatever property you want to use as the string representation
}

    public function getLikes(): ?int
    {
        return $this->Likes;
    }

    public function setLikes(?int $Likes): self
    {
        $this->Likes = $Likes;

        return $this;
    }
}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Description')
            ->add('Titre', TextType::class, [
                'label' => 'Titre',
                'constraints' => [
                    new Length(['max' => 50, 'maxMessage' => 'Field must be no more than 50 characters.'])
                ]
         
            ])
            ->add("Save",SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\Actualite;
use App\Form\ActualiteType;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\ActualiteRepository;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/home')]
class ActualiteController extends AbstractController
{


    #[Route('/new', name: 'app_actualite_new', methods: ['GET', 'POST'])]
    public function newnew(Request $request, ActualiteRepository $actualiteRepository): Response
    {
        $actualite = new Actualite();
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->save($actualite, true);

            return $this->redirectToRoute('app_actualite_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/new.html.twig', [
            'actualite' => $actualite,
            'actualites' => $actualiteRepository->findAll(),
            'form' => $form,
        ]);
    }
    #[Route('/newnew', name: 'app_actualite_newnew', methods: ['GET', 'POST'])]
    public function new(Request $request, ActualiteRepository $actualiteRepository): Response
    {
        $actualite = new Actualite();
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->save($actualite, true);

            return $this->redirectToRoute('app_actualite_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/newnew.html.twig', [
            'actualite' => $actualite,
            'actualites' => $actualiteRepository->findAll(),
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_actualite_show', methods: ['GET','POST'])]
    public function show(Actualite $actualite, CommentaireRepository $commentaireRepository, Request $request): Response
    {
        $commentaire = new Commentaire();
        $commentaire->setComments($actualite);


        // create a Commentaire form
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $commentaireRepository->save($commentaire, true);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentaire);
            $entityManager->flush();
            return $this->redirectToRoute('app_actualite_show', ['id' => $actualite->getId()], Response::HTTP_SEE_OTHER);
        }
        


        // handle like button click
        if ($request->isMethod('POST') && $request->request->get('like')) {
            $likes = $actualite->getLikes();
            $newLikes = $likes + 1;
            $actualite->setLikes($newLikes);
            $entityManager->flush();

            return $this->redirectToRoute('app_actualite_show', [
                'id' => $actualite->getId(),
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('actualite/show.html.twig', [
            'actualite' => $actualite,
            'commentaires' => $commentaireRepository->findAll(),
            'form' => $form->createView(),
        ]);
    }




    #[Route('/{id}/edit', name: 'app_actualite_edit', methods: ['GET', 'POST'])]
     function edit(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $actualiteRepository->save($actualite, true);

            return $this->redirectToRoute('app_actualite_show', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form,
        ]);
    }
    #[Route('/{id}', name: 'app_actualite_delete', methods: ['POST'])]
    function delete(Request $request, Actualite $actualite, ActualiteRepository $actualiteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actualite->getId(), $request->request->get('_token'))) {
            $actualiteRepository->remove($actualite, true);
        }

        return $this->redirectToRoute('app_actualite_show', [], Response::HTTP_SEE_OTHER);
    }
 /*   #[Route('/liste', name:'app_actualite_liste', methods: ['GET'])]
    public function liste(ActualiteRepository $actualiteRepository): Response
    {

        return $this->render('actualite/liste.html.twig', [
            'actualites' => $actualiteRepository->findAll(),
        ]);
    }*/

    #[Route('/admin', name:'app_actualite_admin', methods: ['GET'])]
     function admin(ActualiteRepository $actualiteRepository): Response
    {

        return $this->render('actualite/admin.html.twig', [
            'actualites' => $actualites->findAll(),
        ]);
    }


}

templates/actualite/_delete_form.html.twig
<form method="post" action="{{ path('app_actualite_delete', {'id': actualite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actualite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actualite/_form.html.twig
{{ form_start(form) }}

<div class="col-sm-12 col-xl-6">
    <div class="bg-secondary rounded h-100 p-4">
        <h6 class="mb-4">Floating Label</h6>
        <div class="form-floating mb-3">
            {{ form_widget(form.Titre, {'attr': {'class': 'form-control', 'placeholder': 'exp: Breaking news'}}) }}
            {{ form_label(form.Titre, 'News Title') }}
        </div>
        
        <div class="form-floating">
            {{ form_widget(form.Description, {'attr': {'class': 'form-control', 'placeholder': 'News description here', 'style': 'height: 150px;'}}) }}
            {{ form_label(form.Description, 'News Description') }}
        </div>

        <div class="bg-secondary rounded h-100 p-4">
                                        
            {{ form_widget(form.Save, {'attr': {'class': 'btn btn-outline-light m-2', 'label':'Save'}}) }}
                                       
         </div>
    </div>
</div>

{{ form_end(form) }}

templates/actualite/edit.html.twig
{% extends '/backOffice.html.twig' %}
{% block title %}Edit Actualite{% endblock %}

{% block body %}
<div class="container-fluid pt-4 px-20">
        <div class="row g-4">
            <div class="col-sm-20 col-xl-20">
                <div class="bg-secondary rounded h-100 p-4"
    {{ include('actualite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_actualite_new') }}">back to list</a>

    {{ include('actualite/_delete_form.html.twig') }}
    </div>    </div>
    </div>
    </div>

{% endblock %}

templates/actualite/index.html.twig
{% extends 'frontOffice.html.twig' %}

{% block body %}



{% endblock %}

templates/actualite/new.html.twig
{% extends '/backOffice.html.twig' %}

{% block body %}
                  <div class="container-fluid pt-4 px-4">
                    <div class="row g-4">

                      <div class="col-12">
                        <div class="bg-secondary rounded h-100 p-4">
                            <h6 class="mb-4">Responsive Table</h6>
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">News Title</th>
                                            <th scope="col">Description</th>
                                            <th scope="col">Edit</th>
                                            <th scope="col">Delete</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for a in actualites %}

                                        <tr>
                                            <th scope="row">1</th>
                                            <td>{{ a.titre }}</td>
                                            <td>{{ a.description }}</td>
                                           <td><a href="{{ path('app_actualite_edit', {'id': a.id}) }}">Edit</a> </td>


                                        <td><form method="post" action="{{ path('app_actualite_delete', {'id': a.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ a.id) }}">
                                                <button class="btn-danger">Delete</button>
                                            </form></td>
                                      
                                        </tr>
                                              {% endfor %}

                                    </tbody>
                                </table>
                                <a href="{{ path('app_actualite_newnew') }}">Add New</a>

                            </div>
                        </div>
                    </div>

                        
                </div>
            </div>
{% endblock %}

templates/actualite/newnew.html.twig
{% extends '/backOffice.html.twig' %}

{% block title %}New Actualite{% endblock %}

{% block body %}
   <div class="container-fluid pt-4 px-20">
        <div class="row g-4">
            <div class="col-sm-20 col-xl-20">
                <div class="bg-secondary rounded h-100 p-4">

    {{ include('actualite/_form.html.twig') }}

    <a href="{{ path('app_actualite_new') }}">back to list</a>
    </div>    </div>
    </div>
    </div>


{% endblock %}

templates/actualite/show.html.twig
{% extends '/frontOffice.html.twig' %}

{% block body %}

    <div class="item-details-page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <div class="line-dec"></div>
                        <h2>{{actualite.titre}}</h2>
                    </div>
                </div>

                <div class="col-lg-7">
                    <div class="left-image">
                        <img src="../../assets/images/news.jpeg" alt="" style="border-radius: 20px;">
                    </div>
                </div>

                <div class="col-lg-5 align-self-center">
                    <h4>{{actualite.titre}}</h4>
                    <p>{{actualite.description}} </p>

                    <h4>Make a comment :</h4>
                    {{ form_start(form) }}
                    {{ form_row(form.comment) }}
                    {{ form_widget(form) }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                    {{ form_end(form) }}
                    <br>
                    <h4>Previous comments :</h4>
                    {% for commentaire in commentaires %}
                        {% if commentaire.comments.id == actualite.id %}

                            <tr style="body color: white;">
                                <td>{{ commentaire.comment }}</td>
                            </tr>
                            <td>

                                <br>

                            </td>
                            </tr>
                        {% endif %}
                    {% else %}
                        <tr>
                            <td colspan="3">no commants on this post</td>
                        </tr>
                    {% endfor %}

                </div>

            </div>
        </div>
    </div>
    <div class="author-page">
        <div class="container">
            <div class="col-lg-8">
                <div class="right-info">
                    <div class="row">
                        <div class="col-6">
                            <div class="info-item">
                                <i class="fa fa-heart"></i>
                                <h6>{%if actualite.Likes is not empty %}
                                        {{actualite.Likes }}
                                    {% else %}
                                        0
                                    {% endif %} <em>Likes</em></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>





{% endblock %}