src/Entity/SessionBoosting.php
<?php

namespace App\Entity;

use App\Repository\SessionBoostingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionBoostingRepository::class)]
class SessionBoosting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Titre = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    #[ORM\Column]
    private ?int $Nbr_heure = null;

    #[ORM\Column]
    private ?int $Prix = null;

    #[ORM\ManyToOne(inversedBy: 'sessionBoostings')]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNbrHeure(): ?int
    {
        return $this->Nbr_heure;
    }

    public function setNbrHeure(int $Nbr_heure): self
    {
        $this->Nbr_heure = $Nbr_heure;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->Prix;
    }

    public function setPrix(int $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Form/SessionBoostingType.php
<?php

namespace App\Form;

use App\Entity\SessionBoosting;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SessionBoostingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('Description')
            ->add('Nbr_heure')
            ->add('Prix')
            ->add("Save",SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => SessionBoosting::class,
        ]);
    }
}

src/Controller/SessionBoostingController.php
<?php

namespace App\Controller;
use App\Entity\User;
use App\Repository\UserRepository;
use App\Entity\SessionBoosting;
use App\Form\SessionBoostingType;
use App\Repository\SessionBoostingRepository;
use App\Entity\ReservationBooster;
use App\Form\ReservationBoosterType;
use App\Repository\ReservationBoosterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/session/boosting')]
class SessionBoostingController extends AbstractController
{
    #[Route('/', name: 'app_session_boosting_index', methods: ['GET'])]
    public function index(SessionBoostingRepository $sessionBoostingRepository,ReservationBoosterRepository $reservationBoosterRepository): Response
    {
        return $this->render('user/boosterdashboard.html.twig', [
            'session_boostings' => $sessionBoostingRepository->findAll(),
            'reservation_boosters' => $reservationBoosterRepository->findAll(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_session_boosting_new', methods: ['GET', 'POST'])]
    public function new(Request $request,$id, SessionBoostingRepository $sessionBoostingRepository): Response
    {
        $sessionBoosting = new SessionBoosting();
        $user = $this->getDoctrine()->getRepository(User::class)->find($id);
        $sessionBoosting->setUser($user) ;
        $form = $this->createForm(SessionBoostingType::class, $sessionBoosting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionBoostingRepository->save($sessionBoosting, true);

            return $this->redirectToRoute('app_session_boosting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session_boosting/new.html.twig', [
            'session_boosting' => $sessionBoosting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_boosting_show', methods: ['GET'])]
    public function show(SessionBoosting $sessionBoosting): Response
    {
        return $this->render('session_boosting/show.html.twig', [
            'session_boosting' => $sessionBoosting,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_session_boosting_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SessionBoosting $sessionBoosting, SessionBoostingRepository $sessionBoostingRepository): Response
    {
        $form = $this->createForm(SessionBoostingType::class, $sessionBoosting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $sessionBoostingRepository->save($sessionBoosting, true);

            return $this->redirectToRoute('app_session_boosting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session_boosting/edit.html.twig', [
            'session_boosting' => $sessionBoosting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_session_boosting_delete', methods: ['POST'])]
    public function delete(Request $request, SessionBoosting $sessionBoosting, SessionBoostingRepository $sessionBoostingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$sessionBoosting->getId(), $request->request->get('_token'))) {
            $sessionBoostingRepository->remove($sessionBoosting, true);
        }

        return $this->redirectToRoute('app_session_boosting_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/session_boosting/_delete_form.html.twig
<form method="post" action="{{ path('app_session_boosting_delete', {'id': session_boosting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session_boosting.id) }}">
    <br>
    <button class="btn btn-danger">Delete</button>
</form>

templates/session_boosting/_form.html.twig
<div class="item-details-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-heading">
          <div class="line-dec"></div>
          <h2>New <em>Boositng</em> Session.</h2>
        </div>
      </div>
      <div class="col-lg-12">
        {{ form_start(form, {'attr': {'id': 'contact'}}) }}
        <div class="row">
          <div class="col-lg-4">
            <fieldset>
              {{ form_label(form.Titre) }}
              {{ form_widget(form.Titre, {'attr': {'placeholder': 'Ex. Team Wadhah'}}) }}
            </fieldset>
          </div>
          <div class="col-lg-4">
            <fieldset>
              {{ form_label(form.Description) }}
              {{ form_widget(form.Description, {'attr': {'placeholder': 'Give us your idea'}}) }}
            </fieldset>
          </div>
          <div class="col-lg-4">
            <fieldset>
              {{ form_label(form.Nbr_heure) }}
              {{ form_widget(form.Nbr_heure) }}
            </fieldset>
          </div>
          <div class="col-lg-4">
            <fieldset>
              {{ form_label(form.Prix) }}
              {{ form_widget(form.Prix) }}
            </fieldset>
          </div>
          
          <div class="col-lg-8">
            <fieldset>
              {{ form_widget(form.Save, {'attr': {'class': 'orange-button', 'label':'Save'}}) }}
            </fieldset>
          </div>
        </div>
        {{ form_end(form) }}
      </div>
    </div>
  </div>
</div>

templates/session_boosting/edit.html.twig
{% extends 'frontOffice.html.twig' %}

{% block body %}
    <h1>Edit SessionBoosting</h1>

    {{ include('session_boosting/_form.html.twig', {'button_label': 'Update'}) }}

   <a href="{{ path('app_user_show_dashboard', {'id': app.user.id}) }}" class="btn btn-primary btn-lg "> back to list </a>
    {{ include('session_boosting/_delete_form.html.twig') }}
{% endblock %}

templates/session_boosting/new.html.twig
{% extends 'frontOffice.html.twig' %}

{% block body %}

    {{ include('session_boosting/_form.html.twig') }}

{% endblock %}

templates/session_boosting/show.html.twig
{% extends 'frontOffice.html.twig' %}

{% block body %}
    <h1>SessionBoosting</h1>

    <table class="table">
        <tbody>
            <tr>
                <th style="color: white;">Id</th>
                <td style="color: white;">{{ session_boosting.id }}</td>
            </tr>
            <tr>
                <th style="color: white;">Titre</th>
                <td style="color: white;">{{ session_boosting.Titre }}</td>
            </tr>
            <tr>
                <th style="color: white;">Description</th>
                <td style="color: white;">{{ session_boosting.Description }}</td>
            </tr>
            <tr>
                <th style="color: white;">Nbr_heure</th>
                <td style="color: white;">{{ session_boosting.NbrHeure }}</td>
            </tr>
            <tr>
                <th style="color: white;">Prix</th>
                <td style="color: white;">{{ session_boosting.Prix }}</td>
            </tr>
        </tbody>
    </table>
<th>  <form action="{{path('app_payment', {'id': session_boosting.id})}}" method="post">
            
                                            <input type="hidden" name="token"  value="{{csrf_token('myform')}}">

                                            <input type="hidden" name="amount"  value="{{session_boosting.prix}}">

                                            <button class="btn">
                                            <span style="color: white;">Pay with paypal</span>
                                            </button>
                                    </form></th>
    <a href="{{ path('app_user_show_dashboard', {'id': app.user.id}) }}" class="btn btn-primary btn-lg "> back to list </a>
    <a href="{{ path('app_session_boosting_edit', {'id': app.user.id}) }}" class="btn btn-warning btn-lg "> edit</a>
    {{ include('session_boosting/_delete_form.html.twig') }}
{% endblock %}